# AdvancedBan v2 - Coded by Leoko
# 設定ごとに、簡単な説明があります。
# 変更する前に、各説明を注意深くお読みください。
# 詳細については　: https://www.spigotmc.org/resources/advancedban.8695/　をご覧ください
# 開発ページはこちら: http://dev.skamps.eu

# falseに設定すると、SQLDBがローカルデータベースに保存されます
UseMySQL: false

MySQL:
  IP: localhost
  DB-Name: database-name
  Username: admin
  Password: superSecret
  Port: 3306
  Properties: 'verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8'

# コンソールに短いメッセージのみを表示する場合は、falseに設定します
# 起動時とシャットダウン時。
DetailedEnableMessage: true
DetailedDisableMessage: true

# エラーが発生したときにサーバーへの接続を禁止するかどうか
# データベースを使用します。（例：MySQLサーバーがダウンした場合）
LockdownOnError: true

# これは、何も指定されていない場合に表示されるデフォルトの理由になります
DefaultReason: "none"

# サーバーの時刻とユーザーの時刻が異なる場合は、ここを変更します。
# 例: サーバーの時刻: 16:43 | あなたの時刻: 13:43 | TimeDiffは-3に設定する必要があります。
# サーバー時間をコマンドで確認できます　: /systemPrefs
TimeDiff: 0

# このコマンドは、ミュートされたプレーヤーに対して無効になります
# プレーヤーは、 "/minecraft:me"　でバイパスすることはできません
MuteCommands:
- 'me'
- 'say'
- 'action'
- 'eaction'
- 'describe'
- 'edescribe'
- 'eme'
- 'w'
- 'm'
- 'pm'
- 'whisper'
- 'ewhisper'
- 'emsg'
- 'msg'
- 'etell'
- 'tell'
- 'er'
- 'r'
- 'reply'
- 'ereply'
- 'ac'
- 'eac'
- 'amsg'
- 'eamsg'
- 'ehelpop'
- 'p msg'

# これらのプレイヤーはいかなる方法でも罰せられることはありません
# これは、プレーヤーがオフラインの場合にも機能します
# Vaultを使用して、オフラインプレーヤーでも免除権限が機能するようにします
ExemptPlayers:
- 'Leoko'
- 'md5'
- 'dutchy1001'
- 'ItzSomebody'

# %DATE% 変数に使用される日付形式
DateFormat: "dd.MM.yyyy-HH:mm"

# これは、bungeecord serversもしくは、サポートされていないパーミッションシステムを備えたサーバーに役立ちます *-Perms
# したがって、これを有効にすると、ab.*の代わりにab.allを使用したり、ab.ban.*の代わりにab.ban.allを使用したりできます。
# 否定的な権限では機能しません！たとえば、-ab.allは、そのユーザーのすべてのコマンドをブロックしません。
EnableAllPermissionNodes: false

# 外部REST-APIを使用する場合、JSONで応答する必要があります
# 指定されたAPIは、NAME-> UUIDにのみ使用されます
# UUID-> NAMEの場合、公式のMojangAPIまたはInternFetcherのいずれかを使用します
# インターンフェッチャーを使用できるかどうかを確認するには、/systemPerfsを実行してuuidを比較します
# http://NamesMC.com でオンラインで見ることができるものに
# 類似している場合は、InternFetcherを使用することをお勧めします
UUID-Fetcher:
  # 動的にtrueに設定すると、「有効」および「インターン」設定が上書きされます
  # サーバーに最適なuuidフェッチャー設定を自動的に検出します。
  # 推奨事項：問題がない場合は、動的をfalseに設定しないでください。
  # 動的
  Dynamic: true
  # 有効
  Enabled: true
  # インターン
  Intern: false
  REST-API:
    URL: "https://api.mojang.com/users/profiles/minecraft/%NAME%?at=%TIMESTAMP%"
    Key: "id"
  # バックアップAPI
  BackUp-API:
    URL: "https://us.mc-api.net/v3/uuid/%NAME%"
    Key: "uuid"

# これらは警告に対して実行されるコマンドです
# 番号をスキップすると、前のコマンドが実行されます
# 'broadcast' or 'clear %PLAYER%　などのAdvancedBan以外のコマンドを使用することもできます
# 変数: %PLAYER%, %REASON%, %COUNT%
WarnActions:
  3: "kick %PLAYER% &c&oあなたは3回目の警告を受けました！!"
  4: "tempban %PLAYER% 30m &c&o4回目の警告を受け取りました！"
  5: "tempban %PLAYER% 5h &c&o5回目の警告を受け取りました！"
  6: "tempban %PLAYER% 7d &c&o6回目の警告を受け取りました！"
  7: "tempban %PLAYER% 1mo &c&o%COUNT%番目の警告を受け取りました！"
  10: "ban %PLAYER% &c&o10回目の警告を受け取りました!"

# ここでは、max-punishment-durationのpermission-nodesを作成できます。
# 許可「ab.tempban.dur.1」は、プレーヤーが最大禁止することを許可します。600秒= 10分
# 許可「ab.tempwarn.dur.2」により、プレーヤーは最大で警告することができます。3600秒= 1時間
# 作成できるパーマは10個までです。パーマは「ab.COMMAND.dur.max」で上書きできます
TempPerms:
  1: 600
  2: 3600
  3: 43200

# これをアクティブにすると、エラーなどの詳細情報がコンソールに表示されます。
# プラグインが正しく機能するため、プラグインをアクティブ化することはお勧めしません
# バグを見つけるために設計されています。
Debug: false

# これは plugins/AdvancedBan/logs フォルダーにプラグインログを保持する必要がある日数です。
# デフォルトでは10日に設定されています。
Log Purge Days: 10

# すべてのメッセージでプラグインのプレフィックスを削除します。
Disable Prefix: false

# よりわかりやすい方法でコマンドを登録する
# デフォルトでオフになっているため、AdvancedBanは他のプラグインからの /ban をオーバーライドできます
# これはBukkit固有のオプションです。BungeeCordでは意味がありません
Friendly Register Commands: false
